### PR TITLE
Update HDF 1.2.0.0 to HDF 1.2.0.1

### PR DESCRIPTION
**Pull request by ZacBlanco**

### CODE REVIEW

**Comment by abajwa-hw** [comment]
@ZacBlanco thanks. Did you test this out? I think you would also need to change params.py line e.g.
nifi_dirname = 'HDF-1.2.0.1-1'
https://github.com/abajwa-hw/ambari-nifi-service/blob/master/package/scripts/params.py#L16

Also master.py seems to have extra indentation which Ambari probably won't like
https://github.com/abajwa-hw/ambari-nifi-service/pull/10/files#diff-6b82c0347df0a488fe15e9d9e218d0dfR36

**Comment by ZacBlanco** [comment]
Whoops. No I didn't actually test it. Let me do a quick check

**Comment by ZacBlanco** [comment]
I'm making some additional changes so that the versions and build numbers line up- should be done shortly

**Comment by ZacBlanco** [comment]
It's working. Some images below

image

image

image

image

(It looks like someone forgot to change a version number in the last image)

**Comment by abajwa-hw** [comment]
Awesome thanks!

**Pull request merged**
